AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Max: 25
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Max: 35
  Exclude:
    - test/**/*.rb

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false
