AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 20

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false
