AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Max: 32
  Exclude:
    - test/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 35
  Exclude:
    - test/**/*.rb

Naming/MethodParameterName:
  AllowedNames: x, y, z

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false
